### PR TITLE
features and test for precompile

### PR DESCRIPTION
**Pull request by jvanasco**
allows mako templates to be precompiled for forked containers.

### CODE REVIEW

**Comment by bertjwregeer** [comment]
Could you please rebase on master. I've added testing on Travis and Appveyor (the latter will fail, ignore it for now).

**Comment by mmerickel** [comment]
The search path is only one mechanism for loading templates from pyramid_mako. For this to be more useful I'd prefer that the `precompile` option accepted a list of asset specs to folders and / or templates that should be compiled. Then it can be used to find things that are not on the default search path and if you want it to use the search path then you can just add it.

```ini
mako.directories = myapp:templates/
mako.precompile =
    myapp:templates/
    myapp:some_other_template.mako
```

**Comment by jvanasco** [comment]
That's a great idea.  I'll give it a shot.

**Comment by bertjwregeer** [comment]
To get the test to pass coverage, make sure that you have a directory within the initial directory so that it is recursively called.

**Comment by jvanasco** [comment]
closing for a resubmission in new branch.

**Comment by mmerickel** [comment]
There's no need to close this, you can just force-push to the branch to update the PR. It's always a shame to link to a new PR and lose the original discussion references.

**Comment by jvanasco** [comment]
Ok.  I was going to link back in the new one.  I had to nuke the branch during a rebase, but I realized I can force-push the new branch into this old one's name.

**Pull request closed without merging**
